INSERT INTO jpkiebpm_widgetinfo (id,pagecode,framepos_online,framepos_draft,widget_type,information_online,information_draft) VALUES (12,'homepage',7,7,'bpm-datatype-form','<?xml version="1.0" encoding="UTF-8"?>
<properties><property key="containerId">mortgage</property><property key="processId">com.redhat.bpms.examples.mortgage.MortgageApplication</property></properties>
','<?xml version="1.0" encoding="UTF-8"?>
<properties><property key="containerId">mortgage</property><property key="processId">com.redhat.bpms.examples.mortgage.MortgageApplication</property></properties>
');
INSERT INTO jpkiebpm_widgetinfo (id,pagecode,framepos_online,framepos_draft,widget_type,information_online,information_draft) VALUES (21,'lender',9,9,'bpm-datatable','<?xml version="1.0" encoding="UTF-8"?>
<properties><property key="field_containerId">field_containerId</property><property key="field_processDefinitionId">field_processDefinitionId</property><property key="position_id">1</property><property key="visible_processInstanceId">false</property><property key="field_priority">field_priority</property><property key="visible_activated">true</property><property key="groups">broker,</property><property key="visible_containerId">false</property><property key="position_name">2</property><property key="visible_owner">true</property><property key="processId">com.redhat.bpms.examples.mortgage.MortgageApplication</property><property key="visible_name">true</property><property key="visible_created">true</property><property key="field_created">field_created</property><property key="field_status">field_status</property><property key="visible_skipable">true</property><property key="field_desc">field_desc</property><property key="position_created">9</property><property key="position_skipable">7</property><property key="field_id">field_id</property><property key="visible_parentId">false</property><property key="visible_status">true</property><property key="position_containerId">13</property><property key="position_parentId">14</property><property key="visible_id">true</property><property key="field_owner">field_owner</property><property key="position_activated">10</property><property key="position_owner">8</property><property key="field_processInstanceId">field_processInstanceId</property><property key="position_processInstanceId">11</property><property key="position_processDefinitionId">12</property><property key="visible_subject">true</property><property key="field_skipable">field_skipable</property><property key="field_subject">field_subject</property><property key="position_desc">4</property><property key="position_subject">3</property><property key="field_parentId">field_parentId</property><property key="position_status">5</property><property key="visible_desc">true</property><property key="visible_priority">true</property><property key="position_priority">6</property><property key="containerId">mortgage</property><property key="visible_processDefinitionId">false</property><property key="field_activated">field_activated</property><property key="field_name">field_name</property></properties>
','<?xml version="1.0" encoding="UTF-8"?>
<properties><property key="field_containerId">field_containerId</property><property key="field_processDefinitionId">field_processDefinitionId</property><property key="position_id">1</property><property key="visible_processInstanceId">false</property><property key="field_priority">field_priority</property><property key="visible_activated">true</property><property key="groups">broker,</property><property key="visible_containerId">false</property><property key="position_name">2</property><property key="visible_owner">true</property><property key="processId">com.redhat.bpms.examples.mortgage.MortgageApplication</property><property key="visible_name">true</property><property key="visible_created">true</property><property key="field_created">field_created</property><property key="field_status">field_status</property><property key="visible_skipable">true</property><property key="field_desc">field_desc</property><property key="position_created">9</property><property key="position_skipable">7</property><property key="field_id">field_id</property><property key="visible_parentId">false</property><property key="visible_status">true</property><property key="position_containerId">13</property><property key="position_parentId">14</property><property key="visible_id">true</property><property key="field_owner">field_owner</property><property key="position_activated">10</property><property key="position_owner">8</property><property key="field_processInstanceId">field_processInstanceId</property><property key="position_processInstanceId">11</property><property key="position_processDefinitionId">12</property><property key="visible_subject">true</property><property key="field_skipable">field_skipable</property><property key="field_subject">field_subject</property><property key="position_desc">4</property><property key="position_subject">3</property><property key="field_parentId">field_parentId</property><property key="position_status">5</property><property key="visible_desc">true</property><property key="visible_priority">true</property><property key="position_priority">6</property><property key="containerId">mortgage</property><property key="visible_processDefinitionId">false</property><property key="field_activated">field_activated</property><property key="field_name">field_name</property></properties>
');
